version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"
  - package-ecosystem: "npm"
    directory: "/cmd/hawkward-gui/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
