// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1, arg2) {
  return window['go']['app']['AIOps']['AskAI'](arg1, arg2);
}

export function Chat(arg1) {
  return window['go']['app']['AIOps']['Chat'](arg1);
}

export function DetectAnomalies() {
  return window['go']['app']['AIOps']['DetectAnomalies']();
}

export function GenerateReport(arg1) {
  return window['go']['app']['AIOps']['GenerateReport'](arg1);
}

export function GetOllamaStatus() {
  return window['go']['app']['AIOps']['GetOllamaStatus']();
}

export function WithTimeout(arg1) {
  return window['go']['app']['AIOps']['WithTimeout'](arg1);
}
