// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Chat(arg1:string):Promise<string>;

export function DetectAnomalies():Promise<Array<app.AnomalyInfo>>;

export function GenerateReport(arg1:Array<string>):Promise<string>;

export function GetOllamaStatus():Promise<app.OllamaStatus>;
