// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {app} from '../models';
import {time} from '../models';

export function AskAI(arg1:context.Context,arg2:string):Promise<string>;

export function Chat(arg1:string):Promise<string>;

export function DetectAnomalies():Promise<Array<app.AnomalyInfo>>;

export function GenerateReport(arg1:Array<string>):Promise<string>;

export function GetOllamaStatus():Promise<app.OllamaStatus>;

export function WithTimeout(arg1:time.Duration):Promise<context.Context|context.CancelFunc>;
