// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2, arg3);
}
