// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetAppInfo():Promise<app.AppInfo>;

export function OpenFileDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;
