// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevProcesses() {
  return window['go']['app']['DevOps']['GetDevProcesses']();
}

export function GetPowerShellWorkflows() {
  return window['go']['app']['DevOps']['GetPowerShellWorkflows']();
}

export function GetServices() {
  return window['go']['app']['DevOps']['GetServices']();
}

export function KillProcess(arg1) {
  return window['go']['app']['DevOps']['KillProcess'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['app']['DevOps']['ListDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['app']['DevOps']['ReadFile'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['app']['DevOps']['RunCommand'](arg1);
}

export function RunCommandLive(arg1, arg2) {
  return window['go']['app']['DevOps']['RunCommandLive'](arg1, arg2);
}

export function RunPowerShell(arg1) {
  return window['go']['app']['DevOps']['RunPowerShell'](arg1);
}

export function SearchLog(arg1, arg2) {
  return window['go']['app']['DevOps']['SearchLog'](arg1, arg2);
}

export function TailLog(arg1, arg2) {
  return window['go']['app']['DevOps']['TailLog'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['app']['DevOps']['WriteFile'](arg1, arg2);
}
