// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ExportLogs(arg1:string):Promise<string>;

export function GetLogs(arg1:string,arg2:string,arg3:number):Promise<Array<app.LogEntry>>;

export function SaveLogsToFile(arg1:string,arg2:string):Promise<string>;
