// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DNSLookup(arg1, arg2, arg3) {
  return window['go']['app']['NetOps']['DNSLookup'](arg1, arg2, arg3);
}

export function GetConnections() {
  return window['go']['app']['NetOps']['GetConnections']();
}

export function GetInterfaces() {
  return window['go']['app']['NetOps']['GetInterfaces']();
}

export function Ping(arg1, arg2) {
  return window['go']['app']['NetOps']['Ping'](arg1, arg2);
}

export function PortScan(arg1, arg2) {
  return window['go']['app']['NetOps']['PortScan'](arg1, arg2);
}

export function Traceroute(arg1) {
  return window['go']['app']['NetOps']['Traceroute'](arg1);
}
