// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AllMetricNames():Promise<Array<app.MetricDef>>;

export function ClearPipeline():Promise<void>;

export function GetForecast(arg1:string,arg2:number):Promise<Array<number>>;

export function GetMetricHistory(arg1:string,arg2:number):Promise<Array<number>>;

export function GetMetricWithForecast(arg1:string):Promise<app.MetricHistory>;

export function GetTrend(arg1:string):Promise<app.TrendInfo>;

export function GetWindowStats(arg1:string):Promise<app.StatsInfo>;

export function UpdateSettings(arg1:number,arg2:number):Promise<void>;
