// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefenderStatus() {
  return window['go']['app']['SecOps']['GetDefenderStatus']();
}

export function GetFirewallRules() {
  return window['go']['app']['SecOps']['GetFirewallRules']();
}

export function GetListeningPorts() {
  return window['go']['app']['SecOps']['GetListeningPorts']();
}

export function GetScheduledTasks() {
  return window['go']['app']['SecOps']['GetScheduledTasks']();
}

export function GetSecurityEvents() {
  return window['go']['app']['SecOps']['GetSecurityEvents']();
}

export function GetUsers() {
  return window['go']['app']['SecOps']['GetUsers']();
}
