// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetDefenderStatus():Promise<app.DefenderStatus>;

export function GetFirewallRules():Promise<Array<app.FirewallRule>>;

export function GetListeningPorts():Promise<Array<app.ListeningPort>>;

export function GetScheduledTasks():Promise<Array<app.ScheduledTask>>;

export function GetSecurityEvents():Promise<Array<app.SecurityEvent>>;

export function GetUsers():Promise<Array<app.UserInfo>>;
