// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetCPUInfo():Promise<app.CPUInfo>;

export function GetDiskInfo():Promise<app.DiskInfo>;

export function GetMemoryInfo():Promise<app.MemoryInfo>;

export function GetProcessTree():Promise<Array<app.ProcessInfo>>;

export function GetSystemInfo():Promise<app.SystemInfo>;

export function GetTopProcesses(arg1:number):Promise<Array<app.ProcessInfo>>;

export function ListAllProcesses(arg1:number):Promise<Array<app.ProcessInfo>>;
