// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetBatteryInfo():Promise<app.BatteryInfo>;

export function GetCPUInfo():Promise<app.CPUInfo>;

export function GetDiskInfo():Promise<app.DiskInfo>;

export function GetGPUInfo():Promise<app.GPUInfo>;

export function GetMemoryInfo():Promise<app.MemoryInfo>;

export function GetProcessTree():Promise<Array<app.ProcessInfo>>;

export function GetRecommendations():Promise<Array<app.SystemRecommendation>>;

export function GetSystemInfo():Promise<app.SystemInfo>;

export function GetTopProcesses(arg1:number):Promise<Array<app.ProcessInfo>>;

export function ListAllProcesses(arg1:number):Promise<Array<app.ProcessInfo>>;
