// Code generated by tool. DO NOT EDIT.
//go:build !windows

package sysops

// BatteryInfo holds battery information.
type BatteryInfo struct {
	Percent     float64
	Charging    bool
	TimeLeftSec int64
	Status      string
	Detected    bool
}

// GetBatteryInfo returns nil on non-Windows platforms.
func GetBatteryInfo() *BatteryInfo {
	return &BatteryInfo{Detected: false}
}
