package secops

import (
	"testing"
)

// ---------------------------------------------------------------------------
// parseFirewallRules tests (firewall.go)
// ---------------------------------------------------------------------------

func TestParseFirewallRules_Standard(t *testing.T) {
	output := `Rule Name:                            Block TCP 3389
----------------------------------------------------------------------
Enabled:                              Yes
Direction:                            In
Profiles:                             Domain
LocalIP:                              Any
RemoteIP:                             Any
Protocol:                             TCP
LocalPort:                            3389
RemotePort:                           Any
Action:                               Block

Rule Name:                            Allow HTTP 80
----------------------------------------------------------------------
Enabled:                              Yes
Direction:                            In
Profiles:                             Public
Protocol:                             TCP
LocalPort:                            80
Action:                               Allow

Rule Name:                            Disabled Rule
----------------------------------------------------------------------
Enabled:                              No
Direction:                            Out
Protocol:                             Any
Action:                               Block
`
	rules, err := parseFirewallRules(output)
	if err != nil {
		t.Fatalf("parseFirewallRules returned error: %v", err)
	}
	if len(rules) != 3 {
		t.Fatalf("got %d rules, want 3", len(rules))
	}

	// First rule
	if rules[0].Name != "Block TCP 3389" {
		t.Errorf("rules[0].Name = %q, want %q", rules[0].Name, "Block TCP 3389")
	}
	if !rules[0].Enabled {
		t.Error("rules[0].Enabled = false, want true")
	}
	if rules[0].Direction != "In" {
		t.Errorf("rules[0].Direction = %q, want %q", rules[0].Direction, "In")
	}
	if rules[0].Protocol != "TCP" {
		t.Errorf("rules[0].Protocol = %q, want %q", rules[0].Protocol, "TCP")
	}
	if rules[0].LocalPort != "3389" {
		t.Errorf("rules[0].LocalPort = %q, want %q", rules[0].LocalPort, "3389")
	}
	if rules[0].Action != "Block" {
		t.Errorf("rules[0].Action = %q, want %q", rules[0].Action, "Block")
	}

	// Third rule (disabled)
	if rules[2].Enabled {
		t.Error("rules[2].Enabled = true, want false")
	}
	if rules[2].Action != "Block" {
		t.Errorf("rules[2].Action = %q, want %q", rules[2].Action, "Block")
	}
}

func TestParseFirewallRules_Empty(t *testing.T) {
	rules, err := parseFirewallRules("")
	if err != nil {
		t.Fatalf("parseFirewallRules('') returned error: %v", err)
	}
	if len(rules) != 0 {
		t.Errorf("got %d rules, want 0", len(rules))
	}
}

func TestParseFirewallRules_NoRules(t *testing.T) {
	output := `No rules match the specified criteria.`
	rules, err := parseFirewallRules(output)
	if err != nil {
		t.Fatalf("parseFirewallRules returned error: %v", err)
	}
	if len(rules) != 0 {
		t.Errorf("got %d rules, want 0", len(rules))
	}
}

// ---------------------------------------------------------------------------
// parseIPTablesSave tests (firewall.go)
// ---------------------------------------------------------------------------

func TestParseIPTablesSave(t *testing.T) {
	output := `*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -s 10.0.0.0/8 -j DROP
-A FORWARD -p tcp --dport 443 -j ACCEPT
COMMIT
`
	rules, err := parseIPTablesSave(output)
	if err != nil {
		t.Fatalf("parseIPTablesSave returned error: %v", err)
	}
	if len(rules) != 4 {
		t.Fatalf("got %d rules, want 4", len(rules))
	}
	if rules[0].Action != "Allow" {
		t.Errorf("rules[0].Action = %q, want 'Allow'", rules[0].Action)
	}
	if rules[3].Action != "Block" {
		t.Errorf("rules[3].Action = %q, want 'Block'", rules[3].Action)
	}
}

func TestParseIPTablesSave_Empty(t *testing.T) {
	rules, err := parseIPTablesSave("")
	if err != nil {
		t.Fatalf("parseIPTablesSave('') returned error: %v", err)
	}
	if len(rules) != 0 {
		t.Errorf("got %d rules, want 0", len(rules))
	}
}

func TestParseIPTablesSave_Comments(t *testing.T) {
	output := `# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 443 -j ACCEPT
COMMIT
`
	rules, err := parseIPTablesSave(output)
	if err != nil {
		t.Fatalf("parseIPTablesSave returned error: %v", err)
	}
	if len(rules) != 1 {
		t.Fatalf("got %d rules, want 1", len(rules))
	}
	if rules[0].LocalPort != "443" {
		t.Errorf("rules[0].LocalPort = %q, want '443'", rules[0].LocalPort)
	}
}

// ---------------------------------------------------------------------------
// parseDefenderJSON tests (defender.go)
// ---------------------------------------------------------------------------

func TestParseDefenderJSON_Standard(t *testing.T) {
	jsonStr := `{
		"AMServiceEnabled": true,
		"AntispywareEnabled": true,
		"NISEnabled": true,
		"RealTimeProtectionEnabled": true,
		"CloudProtectionEnabled": false,
		"AntivirusEnabled": true,
		"SignatureAge": 2,
		"QuickScanAge": 1,
		"FullScanAge": 5,
		"QuickScanEndTime": "2026-07-08T10:00:00Z",
		"FullScanEndTime": "2026-07-01T10:00:00Z"
	}`
	status, err := parseDefenderJSON(jsonStr)
	if err != nil {
		t.Fatalf("parseDefenderJSON returned error: %v", err)
	}
	if !status.Enabled {
		t.Error("Enabled = false, want true")
	}
	if !status.AMServiceEnabled {
		t.Error("AMServiceEnabled = false, want true")
	}
	if status.CloudProtection {
		t.Error("CloudProtection = true, want false")
	}
	if !status.UpToDate {
		t.Error("UpToDate = false, want true (SignatureAge=2 <= 7)")
	}
	if status.SignatureAge != "2 days ago" {
		t.Errorf("SignatureAge = %q, want '2 days ago'", status.SignatureAge)
	}
	if status.LastScan != "Quick: 2026-07-08 10:00:00" {
		t.Errorf("LastScan = %q, want 'Quick: 2026-07-08 10:00:00'", status.LastScan)
	}
	if status.QuickScanAge != 1 {
		t.Errorf("QuickScanAge = %d, want 1", status.QuickScanAge)
	}
	if status.FullScanAge != 5 {
		t.Errorf("FullScanAge = %d, want 5", status.FullScanAge)
	}
}

func TestParseDefenderJSON_Empty(t *testing.T) {
	_, err := parseDefenderJSON("{}")
	if err != nil {
		t.Fatalf("parseDefenderJSON('{}') returned error: %v", err)
	}
}

func TestParseDefenderJSON_Invalid(t *testing.T) {
	_, err := parseDefenderJSON("{invalid}")
	if err == nil {
		t.Error("parseDefenderJSON('{invalid}') expected error, got nil")
	}
}

func TestParseDefenderJSON_NoData(t *testing.T) {
	_, err := parseDefenderJSON("null")
	if err == nil {
		t.Error("parseDefenderJSON('null') expected error, got nil")
	}
}

// ---------------------------------------------------------------------------
// parseDefenderPreferenceJSON tests (defender.go)
// ---------------------------------------------------------------------------

func TestParseDefenderPreferenceJSON(t *testing.T) {
	jsonStr := `{
		"DisableRealtimeMonitoring": false,
		"DisableIOAVProtection": false,
		"DisableBehaviorMonitoring": true
	}`
	status, err := parseDefenderPreferenceJSON(jsonStr)
	if err != nil {
		t.Fatalf("parseDefenderPreferenceJSON returned error: %v", err)
	}
	if !status.Enabled {
		t.Error("Enabled = false, want true")
	}
	if !status.RealTimeProtection {
		t.Error("RealTimeProtection = false, want true (DisableRealtimeMonitoring=false)")
	}
	if status.SignatureAge != "Unknown" {
		t.Errorf("SignatureAge = %q, want 'Unknown'", status.SignatureAge)
	}
}

func TestParseDefenderPreferenceJSON_Disabled(t *testing.T) {
	jsonStr := `{
		"DisableRealtimeMonitoring": true
	}`
	status, err := parseDefenderPreferenceJSON(jsonStr)
	if err != nil {
		t.Fatalf("parseDefenderPreferenceJSON returned error: %v", err)
	}
	if status.RealTimeProtection {
		t.Error("RealTimeProtection = true, want false (DisableRealtimeMonitoring=true)")
	}
}

// ---------------------------------------------------------------------------
// parseDefenderWMIC tests (defender.go)
// ---------------------------------------------------------------------------

func TestParseDefenderWMIC(t *testing.T) {
	csvStr := `Node,AntivirusEnabled,AMServiceEnabled,AntispywareEnabled,NISEnabled,RealTimeProtectionEnabled,CloudProtectionEnabled,SignatureAge,QuickScanAge,FullScanAge,QuickScanEndTime,FullScanEndTime
MYPC,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,3,1,10,20260708100000.000000+000,20260701090000.000000+000
`
	status, err := parseDefenderWMIC(csvStr)
	if err != nil {
		t.Fatalf("parseDefenderWMIC returned error: %v", err)
	}
	if !status.Enabled {
		t.Error("Enabled = false, want true")
	}
	if !status.RealTimeProtection {
		t.Error("RealTimeProtection = false, want true")
	}
	if status.CloudProtection {
		t.Error("CloudProtection = true, want false")
	}
	if status.SignatureAge != "3 days ago" {
		t.Errorf("SignatureAge = %q, want '3 days ago'", status.SignatureAge)
	}
	if status.QuickScanAge != 1 {
		t.Errorf("QuickScanAge = %d, want 1", status.QuickScanAge)
	}
	if status.FullScanAge != 10 {
		t.Errorf("FullScanAge = %d, want 10", status.FullScanAge)
	}
}

func TestParseDefenderWMIC_Empty(t *testing.T) {
	_, err := parseDefenderWMIC("")
	if err == nil {
		t.Error("parseDefenderWMIC('') expected error, got nil")
	}
}

// ---------------------------------------------------------------------------
// WMIC helper tests (defender.go)
// ---------------------------------------------------------------------------

func TestWMICBool(t *testing.T) {
	tests := []struct {
		key   string
		value string
		want  bool
	}{
		{"Test", "TRUE", true},
		{"Test", "true", true},
		{"Test", "1", true},
		{"Test", "FALSE", false},
		{"Test", "false", false},
		{"Test", "0", false},
		{"Test", "", false},
	}
	for _, tt := range tests {
		data := map[string]string{tt.key: tt.value}
		got := wmicBool(data, tt.key)
		if got != tt.want {
			t.Errorf("wmicBool(%q, %q) = %v, want %v", tt.key, tt.value, got, tt.want)
		}
	}
}

func TestWMICBool_Missing(t *testing.T) {
	if wmicBool(map[string]string{}, "Missing") {
		t.Error("wmicBool for missing key = true, want false")
	}
}

func TestWMICInt(t *testing.T) {
	tests := []struct {
		key   string
		value string
		want  int
		ok    bool
	}{
		{"Age", "5", 5, true},
		{"Age", "2.0000000000", 2, true},
		{"Age", "0", 0, true},
		{"Age", "", 0, false},
		{"Age", "abc", 0, false},
	}
	for _, tt := range tests {
		data := map[string]string{tt.key: tt.value}
		got, ok := wmicInt(data, tt.key)
		if ok != tt.ok || got != tt.want {
			t.Errorf("wmicInt(%q, %q) = (%d, %v), want (%d, %v)", tt.key, tt.value, got, ok, tt.want, tt.ok)
		}
	}
}

// ---------------------------------------------------------------------------
// formatAge tests (defender.go)
// ---------------------------------------------------------------------------

func TestFormatAge(t *testing.T) {
	tests := []struct {
		days int
		want string
	}{
		{0, "Today"},
		{1, "1 day ago"},
		{2, "2 days ago"},
		{29, "29 days ago"},
		{30, "1 month ago"},
		{60, "2 months ago"},
	}
	for _, tt := range tests {
		got := formatAge(tt.days)
		if got != tt.want {
			t.Errorf("formatAge(%d) = %q, want %q", tt.days, got, tt.want)
		}
	}
}

// ---------------------------------------------------------------------------
// formatTimeStr tests (defender.go)
// ---------------------------------------------------------------------------

func TestFormatTimeStr(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"2026-07-08T10:00:00Z", "2026-07-08 10:00:00"},
		{"2026-07-08T10:00:00.000000+000", "2026-07-08 10:00:00"},
		{"2026-07-08 10:00:00", "2026-07-08 10:00:00"},
		{"", ""},
	}
	for _, tt := range tests {
		got := formatTimeStr(tt.input)
		if got != tt.want {
			t.Errorf("formatTimeStr(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

// ---------------------------------------------------------------------------
// parseNetUserList tests (users.go)
// ---------------------------------------------------------------------------

func TestParseNetUserList(t *testing.T) {
	output := `User accounts for \\MYPC

-------------------------------------------------------------------------------
Administrator            DefaultAccount           Guest
JohnDoe                  WDAGUtilityAccount       TestUser
The command completed successfully.
`
	users := parseNetUserList(output)
	if len(users) != 4 {
		t.Fatalf("got %d users, want 4 (expecting: Administrator, Guest, JohnDoe, TestUser)", len(users))
	}
	if users[0] != "Administrator" {
		t.Errorf("users[0] = %q, want 'Administrator'", users[0])
	}
}

func TestParseNetUserList_Empty(t *testing.T) {
	users := parseNetUserList("")
	if len(users) != 0 {
		t.Errorf("got %d users, want 0", len(users))
	}
}

func TestParseNetUserList_NoUsers(t *testing.T) {
	output := `The command completed successfully.`
	users := parseNetUserList(output)
	if len(users) != 0 {
		t.Errorf("got %d users, want 0", len(users))
	}
}

// ---------------------------------------------------------------------------
// parseNetUserDetail tests (users.go)
// ---------------------------------------------------------------------------

func TestParseNetUserDetail(t *testing.T) {
	output := `User name                    JohnDoe
Full Name                    John Doe
Comment
User's comment
Account active               Yes
Account expires              Never

Local Group Memberships      *Administrators
Global Group memberships     *None
`
	user := parseNetUserDetail(output, "JohnDoe")
	if user.Username != "JohnDoe" {
		t.Errorf("Username = %q, want 'JohnDoe'", user.Username)
	}
	if user.FullName != "John Doe" {
		t.Errorf("FullName = %q, want 'John Doe'", user.FullName)
	}
	if !user.IsEnabled {
		t.Error("IsEnabled = false, want true")
	}
	if !user.IsAdmin {
		t.Error("IsAdmin = false, want true")
	}
	if user.Group != "Administrators" {
		t.Errorf("Group = %q, want 'Administrators'", user.Group)
	}
}

func TestParseNetUserDetail_Disabled(t *testing.T) {
	output := `User name                    TestUser
Full Name                    Test User
Account active               No
Local Group Memberships      *Users
`
	user := parseNetUserDetail(output, "TestUser")
	if user.IsEnabled {
		t.Error("IsEnabled = true, want false")
	}
	if user.Group != "Users" {
		t.Errorf("Group = %q, want 'Users'", user.Group)
	}
}

func TestParseNetUserDetail_Empty(t *testing.T) {
	user := parseNetUserDetail("", "Nobody")
	if user.Username != "Nobody" {
		t.Errorf("Username = %q, want 'Nobody'", user.Username)
	}
}

// ---------------------------------------------------------------------------
// parseNetLocalGroup tests (users.go)
// ---------------------------------------------------------------------------

func TestParseNetLocalGroup(t *testing.T) {
	output := `Aliases for \\MYPC

-------------------------------------------------------------------------------
*Administrators
*Backup Operators
*Guests
*Users
The command completed successfully.
`
	groups := parseNetLocalGroup(output)
	if len(groups) != 4 {
		t.Fatalf("got %d groups, want 4", len(groups))
	}
	if groups[0] != "*Administrators" {
		t.Errorf("groups[0] = %q, want '*Administrators'", groups[0])
	}
}

func TestParseNetLocalGroup_Empty(t *testing.T) {
	groups := parseNetLocalGroup("")
	if len(groups) != 0 {
		t.Errorf("got %d groups, want 0", len(groups))
	}
}

// ---------------------------------------------------------------------------
// splitBySpaces tests (users.go)
// ---------------------------------------------------------------------------

func TestSplitBySpaces(t *testing.T) {
	tests := []struct {
		input string
		want  int
	}{
		{"a b c", 3},
		{"  a   b   c  ", 3},
		{"", 0},
		{"single", 1},
	}
	for _, tt := range tests {
		got := splitBySpaces(tt.input)
		if len(got) != tt.want {
			t.Errorf("splitBySpaces(%q) = %d elements, want %d", tt.input, len(got), tt.want)
		}
	}
}

// ---------------------------------------------------------------------------
// parseListeningPorts tests (listening.go)
// ---------------------------------------------------------------------------

func TestParseListeningPorts(t *testing.T) {
	output := `
  Proto  Local Address          Foreign Address        State           PID
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       1234
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING       5678
  TCP    192.168.1.1:52411      93.184.216.34:443      ESTABLISHED     9012
  UDP    0.0.0.0:1900           *:*                                    3456
  TCP    [::]:445               [::]:0                 LISTENING       7890
`
	ports := parseListeningPorts(output)
	// Expect: 135(TCP), 443(TCP), 1900(UDP), 445(TCP-v6)
	// 52411 is ESTABLISHED, not LISTENING, so excluded
	if len(ports) != 4 {
		t.Fatalf("got %d listening ports, want 4", len(ports))
	}

	portMap := make(map[int]string)
	for _, p := range ports {
		portMap[p.Port] = p.Protocol
	}

	expected := map[int]string{135: "TCP", 443: "TCP", 1900: "UDP", 445: "TCP"}
	for port, proto := range expected {
		if p, ok := portMap[port]; !ok {
			t.Errorf("port %d not found in parsed ports", port)
		} else if p != proto {
			t.Errorf("port %d protocol = %q, want %q", port, p, proto)
		}
	}
}

func TestParseListeningPorts_Empty(t *testing.T) {
	ports := parseListeningPorts("")
	if len(ports) != 0 {
		t.Errorf("got %d ports, want 0", len(ports))
	}
}

// ---------------------------------------------------------------------------
// extractPort tests (listening.go)
// ---------------------------------------------------------------------------

func TestExtractPort(t *testing.T) {
	tests := []struct {
		addr string
		want string
	}{
		{"0.0.0.0:135", "135"},
		{"127.0.0.1:5432", "5432"},
		{"[::]:445", "445"},
		{"[fe80::1%eth0]:8080", "8080"},
		{"*:1900", "1900"},
		{"", ""},
		{"no-port", ""},
	}
	for _, tt := range tests {
		got := extractPort(tt.addr)
		if got != tt.want {
			t.Errorf("extractPort(%q) = %q, want %q", tt.addr, got, tt.want)
		}
	}
}

// ---------------------------------------------------------------------------
// extractPortFromSS tests (listening.go)
// ---------------------------------------------------------------------------

func TestExtractPortFromSS(t *testing.T) {
	tests := []struct {
		addr string
		want string
	}{
		{"[::]:443", "443"},
		{"0.0.0.0:80", "80"},
		{"*:1900", "1900"},
		{"", ""},
		{"no-colon", ""},
	}
	for _, tt := range tests {
		got := extractPortFromSS(tt.addr)
		if got != tt.want {
			t.Errorf("extractPortFromSS(%q) = %q, want %q", tt.addr, got, tt.want)
		}
	}
}

// ---------------------------------------------------------------------------
// parseSSOutput tests (listening.go)
// ---------------------------------------------------------------------------

func TestParseSSOutput(t *testing.T) {
	output := `Netid  State      Recv-Q Send-Q  Local Address:Port          Peer Address:Port         Process
tcp    LISTEN     0      128       0.0.0.0:22                 0.0.0.0:*                users:(("sshd",pid=1234,fd=3))
tcp    LISTEN     0      128       0.0.0.0:443                0.0.0.0:*                users:(("nginx",pid=5678,fd=6))
udp    UNCONN     0      0         0.0.0.0:68                 0.0.0.0:*                users:(("dhclient",pid=9012,fd=7))
`
	ports, err := parseSSOutput(output)
	if err != nil {
		t.Fatalf("parseSSOutput returned error: %v", err)
	}
	if len(ports) != 3 {
		t.Fatalf("got %d ports, want 3", len(ports))
	}

	expected := []struct {
		port    int
		proto   string
		proc    string
		pid     int
	}{
		{22, "TCP", "sshd", 1234},
		{443, "TCP", "nginx", 5678},
		{68, "UDP", "dhclient", 9012},
	}
	for i, exp := range expected {
		if ports[i].Port != exp.port {
			t.Errorf("ports[%d].Port = %d, want %d", i, ports[i].Port, exp.port)
		}
		if ports[i].Protocol != exp.proto {
			t.Errorf("ports[%d].Protocol = %q, want %q", i, ports[i].Protocol, exp.proto)
		}
		if ports[i].ProcessName != exp.proc {
			t.Errorf("ports[%d].ProcessName = %q, want %q", i, ports[i].ProcessName, exp.proc)
		}
		if ports[i].PID != exp.pid {
			t.Errorf("ports[%d].PID = %d, want %d", i, ports[i].PID, exp.pid)
		}
	}
}

func TestParseSSOutput_Empty(t *testing.T) {
	ports, err := parseSSOutput("")
	if err != nil {
		t.Fatalf("parseSSOutput('') returned error: %v", err)
	}
	if len(ports) != 0 {
		t.Errorf("got %d ports, want 0", len(ports))
	}
}

// ---------------------------------------------------------------------------
// parseTasklistCSV tests (listening.go)
// ---------------------------------------------------------------------------

func TestParseTasklistCSV(t *testing.T) {
	output := `"chrome.exe","1234","Console","1","45,678 K"
"nginx.exe","5678","Services","0","12,345 K"
"sshd.exe","9012","Services","0","5,678 K"
`
	pidMap := parseTasklistCSV(output)
	if len(pidMap) != 3 {
		t.Fatalf("got %d entries, want 3", len(pidMap))
	}
	tests := []struct {
		pid  int
		name string
	}{
		{1234, "chrome"},
		{5678, "nginx"},
		{9012, "sshd"},
	}
	for _, tt := range tests {
		name, ok := pidMap[tt.pid]
		if !ok {
			t.Errorf("PID %d not found in map", tt.pid)
		} else if name != tt.name {
			t.Errorf("PID %d name = %q, want %q", tt.pid, name, tt.name)
		}
	}
}

func TestParseTasklistCSV_Empty(t *testing.T) {
	pidMap := parseTasklistCSV("")
	if len(pidMap) != 0 {
		t.Errorf("got %d entries, want 0", len(pidMap))
	}
}

func TestParseTasklistCSV_Invalid(t *testing.T) {
	pidMap := parseTasklistCSV("not,csv,data")
	// Invalid PID "data" should be skipped, resulting in empty map
	if len(pidMap) != 0 {
		t.Errorf("got %d entries, want 0", len(pidMap))
	}
}

// ---------------------------------------------------------------------------
// JSON helper tests (defender.go)
// ---------------------------------------------------------------------------

func TestGetJSONBool(t *testing.T) {
	data := map[string]interface{}{
		"trueVal":  true,
		"falseVal": false,
		"string":   "hello",
		"number":   42,
	}
	if !getJSONBool(data, "trueVal") {
		t.Error("getJSONBool(trueVal) = false, want true")
	}
	if getJSONBool(data, "falseVal") {
		t.Error("getJSONBool(falseVal) = true, want false")
	}
	if getJSONBool(data, "nonexistent") {
		t.Error("getJSONBool(nonexistent) = true, want false")
	}
}

func TestGetJSONInt(t *testing.T) {
	data := map[string]interface{}{
		"floatVal": float64(42),
		"intVal":   42,
		"string":   "hello",
	}
	val, ok := getJSONInt(data, "floatVal")
	if !ok || val != 42 {
		t.Errorf("getJSONInt(floatVal) = (%d, %v), want (42, true)", val, ok)
	}
	val, ok = getJSONInt(data, "nonexistent")
	if ok {
		t.Errorf("getJSONInt(nonexistent) = (%d, %v), want (0, false)", val, ok)
	}
}

func TestGetJSONString(t *testing.T) {
	data := map[string]interface{}{
		"strVal": "hello",
		"numVal": 42,
	}
	val, ok := getJSONString(data, "strVal")
	if !ok || val != "hello" {
		t.Errorf("getJSONString(strVal) = (%q, %v), want (\"hello\", true)", val, ok)
	}
	_, ok = getJSONString(data, "numVal")
	if ok {
		t.Error("getJSONString(numVal) should return false for non-string")
	}
	_, ok = getJSONString(data, "nonexistent")
	if ok {
		t.Error("getJSONString(nonexistent) should return false")
	}
}
