// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddRule(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function EvaluateNow():Promise<Array<app.AlertInfo>>;

export function GetActiveAlerts():Promise<Array<app.AlertInfo>>;

export function GetAlertCount():Promise<number>;

export function GetAlertHistory():Promise<Array<app.AlertInfo>>;

export function RemoveRule(arg1:string,arg2:number):Promise<void>;

export function ResolveAlert(arg1:string):Promise<void>;
