// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['AlertAPI']['AddRule'](arg1, arg2, arg3, arg4);
}

export function EvaluateNow() {
  return window['go']['app']['AlertAPI']['EvaluateNow']();
}

export function GetActiveAlerts() {
  return window['go']['app']['AlertAPI']['GetActiveAlerts']();
}

export function GetAlertCount() {
  return window['go']['app']['AlertAPI']['GetAlertCount']();
}

export function GetAlertHistory() {
  return window['go']['app']['AlertAPI']['GetAlertHistory']();
}

export function GetRules() {
  return window['go']['app']['AlertAPI']['GetRules']();
}

export function RemoveRule(arg1, arg2) {
  return window['go']['app']['AlertAPI']['RemoveRule'](arg1, arg2);
}

export function ResolveAlert(arg1) {
  return window['go']['app']['AlertAPI']['ResolveAlert'](arg1);
}
