// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyOperationalProfile(arg1) {
  return window['go']['app']['App']['ApplyOperationalProfile'](arg1);
}

export function ClearOnboarded() {
  return window['go']['app']['App']['ClearOnboarded']();
}

export function ConfirmAction(arg1) {
  return window['go']['app']['App']['ConfirmAction'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetSystemCapabilities() {
  return window['go']['app']['App']['GetSystemCapabilities']();
}

export function IsOnboarded() {
  return window['go']['app']['App']['IsOnboarded']();
}

export function ListCollectors() {
  return window['go']['app']['App']['ListCollectors']();
}

export function MarkOnboarded() {
  return window['go']['app']['App']['MarkOnboarded']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SetCapabilityOverride(arg1, arg2) {
  return window['go']['app']['App']['SetCapabilityOverride'](arg1, arg2);
}

export function SetCollectorEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetCollectorEnabled'](arg1, arg2);
}

export function SetCollectorInterval(arg1, arg2) {
  return window['go']['app']['App']['SetCollectorInterval'](arg1, arg2);
}

export function SetLogLevel(arg1) {
  return window['go']['app']['App']['SetLogLevel'](arg1);
}

export function TriggerCollector(arg1) {
  return window['go']['app']['App']['TriggerCollector'](arg1);
}

export function UpdateStorageConfig(arg1) {
  return window['go']['app']['App']['UpdateStorageConfig'](arg1);
}
