// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {common} from '../models';

export function ClearOnboarded():Promise<void>;

export function ConfirmAction(arg1:string):Promise<app.SecActionResult>;

export function GetAppInfo():Promise<app.AppInfo>;

export function IsOnboarded():Promise<boolean>;

export function ListCollectors():Promise<Array<common.CollectorStatus>>;

export function MarkOnboarded():Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SetCollectorEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetCollectorInterval(arg1:string,arg2:number):Promise<void>;

export function TriggerCollector(arg1:string):Promise<void>;
