// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {app} from '../models';

export function AnalyzeDatabase():Promise<void>;

export function ApplyOperationalProfile(arg1:string):Promise<void>;

export function ClearOnboarded():Promise<void>;

export function ConfirmAction(arg1:string):Promise<common.SecActionResult>;

export function DiscoverEnvironment():Promise<app.EnvReport>;

export function GenerateBaselineSnapshot():Promise<app.BaselineSnapshot>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetDataDir():Promise<string>;

export function GetLogsDir():Promise<string>;

export function GetPerformanceProfile():Promise<app.PerformanceProfile>;

export function GetSystemCapabilities():Promise<Array<common.CapabilityInfo>>;

export function IsOnboarded():Promise<boolean>;

export function ListCollectors():Promise<Array<common.CollectorStatus>>;

export function MarkOnboarded():Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SelectFolderDialog(arg1:string):Promise<string>;

export function SetCapabilityOverride(arg1:string,arg2:string):Promise<void>;

export function SetCollectorEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetCollectorInterval(arg1:string,arg2:number):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function TriggerCollector(arg1:string):Promise<void>;

export function TriggerWorkflow(arg1:string):Promise<string>;

export function UpdateLogsConfig(arg1:string):Promise<void>;

export function UpdateStorageConfig(arg1:string):Promise<void>;

export function VacuumDatabase():Promise<void>;
