// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDashboardBriefing() {
  return window['go']['app']['Dashboard']['GenerateDashboardBriefing']();
}

export function GetDashboardData() {
  return window['go']['app']['Dashboard']['GetDashboardData']();
}

export function RunQuickDiag() {
  return window['go']['app']['Dashboard']['RunQuickDiag']();
}
