// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDashboardBriefing() {
  return window['go']['app']['Dashboard']['GenerateDashboardBriefing']();
}

export function GetAIOpsSummary() {
  return window['go']['app']['Dashboard']['GetAIOpsSummary']();
}

export function GetDashboardData() {
  return window['go']['app']['Dashboard']['GetDashboardData']();
}

export function GetDevOpsSummary() {
  return window['go']['app']['Dashboard']['GetDevOpsSummary']();
}

export function GetDockerStatus() {
  return window['go']['app']['Dashboard']['GetDockerStatus']();
}

export function GetKubernetesStatus() {
  return window['go']['app']['Dashboard']['GetKubernetesStatus']();
}

export function GetSLODefinitions() {
  return window['go']['app']['Dashboard']['GetSLODefinitions']();
}

export function GetSLOSummary() {
  return window['go']['app']['Dashboard']['GetSLOSummary']();
}

export function GetSecurityScore() {
  return window['go']['app']['Dashboard']['GetSecurityScore']();
}

export function GetSecuritySummary() {
  return window['go']['app']['Dashboard']['GetSecuritySummary']();
}

export function GetSystemSnapshot() {
  return window['go']['app']['Dashboard']['GetSystemSnapshot']();
}

export function RunQuickDiag() {
  return window['go']['app']['Dashboard']['RunQuickDiag']();
}

export function SetSLOEngine(arg1) {
  return window['go']['app']['Dashboard']['SetSLOEngine'](arg1);
}
