// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {common} from '../models';

export function GenerateDashboardBriefing():Promise<Array<app.BriefingSection>>;

export function GetAIOpsSummary():Promise<app.AIOpsSummary>;

export function GetDashboardData():Promise<app.DashboardData>;

export function GetDevOpsSummary():Promise<app.DevOpsSummary>;

export function GetDockerStatus():Promise<app.DockerStatus>;

export function GetKubernetesStatus():Promise<app.KubernetesStatus>;

export function GetSLODefinitions():Promise<Array<common.SLODefinition>>;

export function GetSLOSummary():Promise<common.SLOSummary>;

export function GetSecurityScore():Promise<app.SecurityScore>;

export function GetSecuritySummary():Promise<app.SecuritySummary>;

export function GetSystemSnapshot():Promise<app.SystemSnapshot>;

export function RunQuickDiag():Promise<Array<app.DiagnosticResult>>;

export function SetSLOEngine(arg1:common.SLOEngine):Promise<void>;
