// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GenerateDashboardBriefing():Promise<Array<app.BriefingSection>>;

export function GetDashboardData():Promise<app.DashboardData>;

export function GetSystemSnapshot():Promise<app.SystemSnapshot>;

export function RunQuickDiag():Promise<Array<app.DiagnosticResult>>;
