// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ControlService(arg1:string,arg2:string):Promise<boolean>;

export function GetAISuggestions():Promise<Array<app.DevOpsSuggestion>>;

export function GetContainers():Promise<app.ContainerSummary>;

export function GetDefaultPath():Promise<string>;

export function GetDevProcesses():Promise<Array<app.ProcessInfo>>;

export function GetDockerStatus():Promise<app.DockerStatus>;

export function GetEnvironment():Promise<app.EnvironmentInfo>;

export function GetInstalledTools():Promise<Array<app.ToolInfo>>;

export function GetKubernetesStatus():Promise<app.KubernetesStatus>;

export function GetLocalServers():Promise<Array<app.LocalServer>>;

export function GetServiceCategories():Promise<Array<app.ServiceCategory>>;

export function GetServiceGroupSummary():Promise<app.ServiceGroupSummary>;

export function GetServices():Promise<Array<app.ServiceEntry>>;

export function KillProcess(arg1:number):Promise<app.CommandResult>;

export function RunCommand(arg1:string):Promise<app.CommandResult>;

export function RunCommandLive(arg1:string,arg2:string):Promise<app.CommandResult>;

export function RunDevOpsDiagnostics():Promise<app.DevOpsDiagResult>;

export function RunPowerShellLive(arg1:string,arg2:string):Promise<app.CommandResult>;
