// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ControlService(arg1:string,arg2:string):Promise<boolean>;

export function DockerComposeList():Promise<Array<app.DockerComposeProject>>;

export function DockerKill(arg1:string):Promise<app.DockerActionResult>;

export function DockerPause(arg1:string):Promise<app.DockerActionResult>;

export function DockerPrune():Promise<app.DockerActionResult>;

export function DockerRename(arg1:string,arg2:string):Promise<app.DockerActionResult>;

export function DockerStart(arg1:string):Promise<app.DockerActionResult>;

export function DockerUnpause(arg1:string):Promise<app.DockerActionResult>;

export function GetAISuggestions():Promise<Array<app.DevOpsSuggestion>>;

export function GetContainers():Promise<app.ContainerSummary>;

export function GetDefaultPath():Promise<string>;

export function GetDevProcesses():Promise<Array<app.ProcessInfo>>;

export function GetDockerNetworks():Promise<Array<app.DockerNetworkInfo>>;

export function GetDockerStats():Promise<Array<app.DockerStatsEntry>>;

export function GetDockerStatus():Promise<app.DockerStatus>;

export function GetDockerVolumes():Promise<Array<app.DockerVolumeInfo>>;

export function GetEnvironment():Promise<app.EnvironmentInfo>;

export function GetInstalledTools():Promise<Array<app.ToolInfo>>;

export function GetK8sDeployments(arg1:string):Promise<Array<app.K8sResourceItem>>;

export function GetK8sEvents(arg1:string,arg2:number):Promise<Array<app.K8sEvent>>;

export function GetK8sNamespaces():Promise<Array<app.K8sNamespaceInfo>>;

export function GetK8sPods(arg1:string):Promise<Array<app.K8sResourceItem>>;

export function GetK8sRollouts(arg1:string):Promise<Array<app.K8sRolloutStatus>>;

export function GetK8sServices(arg1:string):Promise<Array<app.K8sResourceItem>>;

export function GetKubernetesStatus():Promise<app.KubernetesStatus>;

export function GetLocalServers():Promise<Array<app.LocalServer>>;

export function GetServiceCategories():Promise<Array<app.ServiceCategory>>;

export function GetServiceGroupSummary():Promise<app.ServiceGroupSummary>;

export function GetServices():Promise<Array<app.ServiceEntry>>;

export function K8sRestartDeployment(arg1:string,arg2:string):Promise<app.K8sActionResult>;

export function K8sRollbackDeployment(arg1:string,arg2:string,arg3:number):Promise<app.K8sActionResult>;

export function KillProcess(arg1:number):Promise<app.CommandResult>;

export function RunCommand(arg1:string):Promise<app.CommandResult>;

export function RunCommandLive(arg1:string,arg2:string):Promise<app.CommandResult>;

export function RunDevOpsDiagnostics():Promise<app.DevOpsDiagResult>;

export function RunGitBashLive(arg1:string,arg2:string):Promise<app.CommandResult>;

export function RunPowerShellLive(arg1:string,arg2:string):Promise<app.CommandResult>;
