// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ControlService(arg1, arg2) {
  return window['go']['app']['DevOps']['ControlService'](arg1, arg2);
}

export function GetAISuggestions() {
  return window['go']['app']['DevOps']['GetAISuggestions']();
}

export function GetContainers() {
  return window['go']['app']['DevOps']['GetContainers']();
}

export function GetDefaultPath() {
  return window['go']['app']['DevOps']['GetDefaultPath']();
}

export function GetDevProcesses() {
  return window['go']['app']['DevOps']['GetDevProcesses']();
}

export function GetDockerStatus() {
  return window['go']['app']['DevOps']['GetDockerStatus']();
}

export function GetEnvironment() {
  return window['go']['app']['DevOps']['GetEnvironment']();
}

export function GetInstalledTools() {
  return window['go']['app']['DevOps']['GetInstalledTools']();
}

export function GetKubernetesStatus() {
  return window['go']['app']['DevOps']['GetKubernetesStatus']();
}

export function GetLocalServers() {
  return window['go']['app']['DevOps']['GetLocalServers']();
}

export function GetPowerShellWorkflows() {
  return window['go']['app']['DevOps']['GetPowerShellWorkflows']();
}

export function GetServiceCategories() {
  return window['go']['app']['DevOps']['GetServiceCategories']();
}

export function GetServiceGroupSummary() {
  return window['go']['app']['DevOps']['GetServiceGroupSummary']();
}

export function GetServices() {
  return window['go']['app']['DevOps']['GetServices']();
}

export function KillProcess(arg1) {
  return window['go']['app']['DevOps']['KillProcess'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['app']['DevOps']['RunCommand'](arg1);
}

export function RunCommandLive(arg1, arg2) {
  return window['go']['app']['DevOps']['RunCommandLive'](arg1, arg2);
}

export function RunDevOpsDiagnostics() {
  return window['go']['app']['DevOps']['RunDevOpsDiagnostics']();
}

export function RunPowerShell(arg1) {
  return window['go']['app']['DevOps']['RunPowerShell'](arg1);
}
