// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GenerateLogSummary():Promise<app.LogSummary>;

export function GetLogStats():Promise<app.LogStats>;

export function GetLogTimeline(arg1:number):Promise<Array<app.LogTimelinePoint>>;

export function GetLogs(arg1:string,arg2:string,arg3:number):Promise<Array<app.LogEntry>>;
