// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DNSLookup(arg1:string,arg2:string,arg3:number):Promise<app.DNSResult>;

export function GetConnections():Promise<Array<app.ConnectionInfo>>;

export function GetInterfaces():Promise<Array<app.InterfaceInfo>>;

export function Ping(arg1:string,arg2:number):Promise<app.PingResult>;

export function PortScan(arg1:string,arg2:Array<number>):Promise<Array<app.PortResult>>;

export function Traceroute(arg1:string):Promise<app.TraceResult>;
