// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {netops} from '../models';

export function DNSLookup(arg1:string,arg2:string,arg3:number):Promise<app.DNSResult>;

export function FlushDNSCache():Promise<Record<string, any>>;

export function GetARPTable():Promise<Array<netops.ARPEntry>>;

export function GetConnections():Promise<Array<app.ConnectionInfo>>;

export function GetDefaultGateway():Promise<app.GatewayInfo>;

export function GetFirewallRules():Promise<Array<app.NetOpsFirewallRuleData>>;

export function GetInterfaces():Promise<Array<app.InterfaceInfo>>;

export function GetNetworkSummary():Promise<app.NetworkSummary>;

export function GetPingStats(arg1:Array<app.PingResultMultiData>):Promise<app.PingStatsData>;

export function GetRecentChanges():Promise<Array<app.NetworkChange>>;

export function GetRoutingTable():Promise<Array<netops.RouteEntry>>;

export function GetVPNStatus():Promise<app.VPNStatusData>;

export function GetWiFiInfo():Promise<netops.WiFiInfo>;

export function Ping(arg1:string,arg2:number):Promise<app.PingResult>;

export function PingMultiTarget(arg1:Array<string>,arg2:number):Promise<Array<app.PingResultMultiData>>;

export function PortScan(arg1:string,arg2:Array<number>):Promise<Array<app.PortResult>>;

export function ReverseLookup(arg1:string):Promise<Record<string, any>>;

export function RunNetworkAction(arg1:string,arg2:Record<string, string>):Promise<app.NetworkActionResult>;

export function RunNetworkDiscovery(arg1:string):Promise<netops.DiscoveryResult>;

export function RunNetworkHealthCheck():Promise<app.NetworkHealthReport>;

export function ScanWiFiNetworks():Promise<Array<netops.WiFiNetwork>>;

export function TestDoH(arg1:string):Promise<app.DoHResultData>;

export function Traceroute(arg1:string):Promise<app.TraceResult>;
