// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {networkdesign} from '../models';

export function AnalyzeTopology():Promise<networkdesign.TopologyHealth>;

export function DiscoverLocalNetwork():Promise<Array<networkdesign.TopologyNode>>;

export function GetInventory():Promise<Record<string, any>>;

export function LoadTopology():Promise<string>;

export function SaveTopology():Promise<networkdesign.TopologyHealth>;

export function SetTopology(arg1:string,arg2:string):Promise<void>;
