// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeTopology() {
  return window['go']['app']['NetworkDesignAPI']['AnalyzeTopology']();
}

export function DiscoverLocalNetwork() {
  return window['go']['app']['NetworkDesignAPI']['DiscoverLocalNetwork']();
}

export function GetInventory() {
  return window['go']['app']['NetworkDesignAPI']['GetInventory']();
}

export function LoadTopology() {
  return window['go']['app']['NetworkDesignAPI']['LoadTopology']();
}

export function SaveTopology() {
  return window['go']['app']['NetworkDesignAPI']['SaveTopology']();
}

export function SetTopology(arg1, arg2) {
  return window['go']['app']['NetworkDesignAPI']['SetTopology'](arg1, arg2);
}
