// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllMetricNames() {
  return window['go']['app']['PipelineAPI']['AllMetricNames']();
}

export function ClearPipeline() {
  return window['go']['app']['PipelineAPI']['ClearPipeline']();
}

export function GetCurrentSettings() {
  return window['go']['app']['PipelineAPI']['GetCurrentSettings']();
}

export function GetForecast(arg1, arg2) {
  return window['go']['app']['PipelineAPI']['GetForecast'](arg1, arg2);
}

export function GetMetricHistory(arg1, arg2) {
  return window['go']['app']['PipelineAPI']['GetMetricHistory'](arg1, arg2);
}

export function GetMetricHistoryWithTimestamps(arg1, arg2) {
  return window['go']['app']['PipelineAPI']['GetMetricHistoryWithTimestamps'](arg1, arg2);
}

export function GetMetricWithForecast(arg1) {
  return window['go']['app']['PipelineAPI']['GetMetricWithForecast'](arg1);
}

export function GetTrend(arg1) {
  return window['go']['app']['PipelineAPI']['GetTrend'](arg1);
}

export function GetWindowStats(arg1) {
  return window['go']['app']['PipelineAPI']['GetWindowStats'](arg1);
}

export function LoadSettings() {
  return window['go']['app']['PipelineAPI']['LoadSettings']();
}

export function PersistSettings() {
  return window['go']['app']['PipelineAPI']['PersistSettings']();
}

export function UpdateSettings(arg1, arg2, arg3, arg4) {
  return window['go']['app']['PipelineAPI']['UpdateSettings'](arg1, arg2, arg3, arg4);
}
