// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function DeleteReport(arg1:string):Promise<boolean>;

export function ListAllReports():Promise<Array<common.ReportRecord>>;
