// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteReport(arg1) {
  return window['go']['app']['ReportsAPI']['DeleteReport'](arg1);
}

export function ListAllReports() {
  return window['go']['app']['ReportsAPI']['ListAllReports']();
}
