// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {app} from '../models';

export function AddReportRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string):Promise<common.AutoReportRule>;

export function AddRuleFromTemplate(arg1:string):Promise<common.AutoReportRule>;

export function DeleteReport(arg1:string):Promise<boolean>;

export function DeleteReportRule(arg1:string):Promise<boolean>;

export function GenerateReport(arg1:string):Promise<app.ReportGenerationResult>;

export function GetEnabledReportRules():Promise<Array<common.AutoReportRule>>;

export function GetPrebuiltTemplates():Promise<Array<app.PrebuiltReportTemplate>>;

export function GetReport(arg1:string):Promise<common.ReportRecord>;

export function GetReportRules():Promise<Array<common.AutoReportRule>>;

export function GetReportTypes():Promise<Array<app.ReportTypeMeta>>;

export function ListAllReports():Promise<Array<common.ReportRecord>>;

export function TouchRule(arg1:string):Promise<void>;

export function TriggerReport(arg1:string):Promise<string>;

export function UpdateReportRule(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;
