// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReportRule(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['ReportsAPI']['AddReportRule'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteReport(arg1) {
  return window['go']['app']['ReportsAPI']['DeleteReport'](arg1);
}

export function DeleteReportRule(arg1) {
  return window['go']['app']['ReportsAPI']['DeleteReportRule'](arg1);
}

export function GenerateReport(arg1) {
  return window['go']['app']['ReportsAPI']['GenerateReport'](arg1);
}

export function GetEnabledReportRules() {
  return window['go']['app']['ReportsAPI']['GetEnabledReportRules']();
}

export function GetReport(arg1) {
  return window['go']['app']['ReportsAPI']['GetReport'](arg1);
}

export function GetReportRules() {
  return window['go']['app']['ReportsAPI']['GetReportRules']();
}

export function GetReportTypes() {
  return window['go']['app']['ReportsAPI']['GetReportTypes']();
}

export function ListAllReports() {
  return window['go']['app']['ReportsAPI']['ListAllReports']();
}

export function TouchRule(arg1) {
  return window['go']['app']['ReportsAPI']['TouchRule'](arg1);
}

export function TriggerReport(arg1) {
  return window['go']['app']['ReportsAPI']['TriggerReport'](arg1);
}

export function UpdateReportRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['ReportsAPI']['UpdateReportRule'](arg1, arg2, arg3, arg4);
}
