// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockIP(arg1) {
  return window['go']['app']['SecOps']['BlockIP'](arg1);
}

export function CaptureEvidence() {
  return window['go']['app']['SecOps']['CaptureEvidence']();
}

export function DisableAccount(arg1) {
  return window['go']['app']['SecOps']['DisableAccount'](arg1);
}

export function ExportForensicBundle() {
  return window['go']['app']['SecOps']['ExportForensicBundle']();
}

export function GetAccountLockouts() {
  return window['go']['app']['SecOps']['GetAccountLockouts']();
}

export function GetDefenderStatus() {
  return window['go']['app']['SecOps']['GetDefenderStatus']();
}

export function GetDiskEncryptionStatus() {
  return window['go']['app']['SecOps']['GetDiskEncryptionStatus']();
}

export function GetEventTimeline() {
  return window['go']['app']['SecOps']['GetEventTimeline']();
}

export function GetFailedLogins() {
  return window['go']['app']['SecOps']['GetFailedLogins']();
}

export function GetFirewallRules() {
  return window['go']['app']['SecOps']['GetFirewallRules']();
}

export function GetFirewallStatus() {
  return window['go']['app']['SecOps']['GetFirewallStatus']();
}

export function GetHardeningChecks() {
  return window['go']['app']['SecOps']['GetHardeningChecks']();
}

export function GetListeningPorts() {
  return window['go']['app']['SecOps']['GetListeningPorts']();
}

export function GetPasswordPolicy() {
  return window['go']['app']['SecOps']['GetPasswordPolicy']();
}

export function GetPrivilegeEvents() {
  return window['go']['app']['SecOps']['GetPrivilegeEvents']();
}

export function GetPublicExposure() {
  return window['go']['app']['SecOps']['GetPublicExposure']();
}

export function GetRisks() {
  return window['go']['app']['SecOps']['GetRisks']();
}

export function GetRunningServices() {
  return window['go']['app']['SecOps']['GetRunningServices']();
}

export function GetSSHConfig() {
  return window['go']['app']['SecOps']['GetSSHConfig']();
}

export function GetScheduledTasks() {
  return window['go']['app']['SecOps']['GetScheduledTasks']();
}

export function GetSecureBootStatus() {
  return window['go']['app']['SecOps']['GetSecureBootStatus']();
}

export function GetSecurityEvents() {
  return window['go']['app']['SecOps']['GetSecurityEvents']();
}

export function GetSecurityScore() {
  return window['go']['app']['SecOps']['GetSecurityScore']();
}

export function GetSecuritySummary() {
  return window['go']['app']['SecOps']['GetSecuritySummary']();
}

export function GetTLSCertificates() {
  return window['go']['app']['SecOps']['GetTLSCertificates']();
}

export function GetUsers() {
  return window['go']['app']['SecOps']['GetUsers']();
}

export function IsolateHost(arg1, arg2) {
  return window['go']['app']['SecOps']['IsolateHost'](arg1, arg2);
}

export function KillProcess(arg1) {
  return window['go']['app']['SecOps']['KillProcess'](arg1);
}

export function RunSecurityAuditChecklist() {
  return window['go']['app']['SecOps']['RunSecurityAuditChecklist']();
}

export function SetFirewallRuleHandshake(arg1, arg2) {
  return window['go']['app']['SecOps']['SetFirewallRuleHandshake'](arg1, arg2);
}
