// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {app} from '../models';

export function BlockIP(arg1:string):Promise<common.ActionPreview>;

export function CaptureEvidence():Promise<common.ActionPreview>;

export function DiffForensics(arg1:string,arg2:string):Promise<app.ForensicDiff>;

export function DisableAccount(arg1:string):Promise<common.ActionPreview>;

export function ExportForensicBundle(arg1:string):Promise<common.ActionPreview>;

export function GetAccountLockouts():Promise<Array<app.LockedAccount>>;

export function GetDefenderStatus():Promise<app.DefenderStatus>;

export function GetDiskEncryptionStatus():Promise<Array<app.DiskEncryption>>;

export function GetEventTimeline():Promise<Array<app.SecTimelineEvent>>;

export function GetFailedLogins():Promise<Array<app.FailedLogin>>;

export function GetFirewallRules():Promise<Array<app.FirewallRule>>;

export function GetFirewallStatus():Promise<app.FirewallStatus>;

export function GetForensic(arg1:string):Promise<common.ForensicRecord>;

export function GetHardeningChecks():Promise<Array<app.HardeningCheck>>;

export function GetHistoricalSecurityReport(arg1:string):Promise<app.SecurityAuditResult>;

export function GetListeningPorts():Promise<Array<app.ListeningPort>>;

export function GetPasswordPolicy():Promise<app.PasswordPolicy>;

export function GetPrivilegeEvents():Promise<Array<app.PrivilegeEvent>>;

export function GetPublicExposure():Promise<Array<app.PublicExposure>>;

export function GetRisks():Promise<Array<app.RiskInfo>>;

export function GetRunningServices():Promise<Array<app.SystemService>>;

export function GetSSHConfig():Promise<app.SSHConfig>;

export function GetScheduledTasks():Promise<Array<app.ScheduledTask>>;

export function GetSecureBootStatus():Promise<app.SecureBoot>;

export function GetSecurityEvents():Promise<Array<app.SecurityEvent>>;

export function GetSecurityScore():Promise<app.SecurityScore>;

export function GetSecuritySummary():Promise<app.SecuritySummary>;

export function GetTLSCertificates():Promise<Array<app.TLSCertificate>>;

export function GetUsers():Promise<Array<app.UserInfo>>;

export function IsolateHost(arg1:boolean,arg2:number):Promise<common.ActionPreview>;

export function KillProcess(arg1:number):Promise<common.ActionPreview>;

export function KillProcessTree(arg1:number):Promise<common.ActionPreview>;

export function ListForensics():Promise<Array<common.ForensicRecord>>;

export function ListHistoricalSecurityReports():Promise<Array<common.ReportRecord>>;

export function RunSecurityAuditChecklist():Promise<app.SecurityAuditResult>;

export function SetFirewallRuleHandshake(arg1:string,arg2:boolean):Promise<common.ActionPreview>;
