// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefenderStatus() {
  return window['go']['app']['SecOps']['GetDefenderStatus']();
}

export function GetFirewallRules() {
  return window['go']['app']['SecOps']['GetFirewallRules']();
}

export function GetFirewallStatus() {
  return window['go']['app']['SecOps']['GetFirewallStatus']();
}

export function GetListeningPorts() {
  return window['go']['app']['SecOps']['GetListeningPorts']();
}

export function GetRisks() {
  return window['go']['app']['SecOps']['GetRisks']();
}

export function GetScheduledTasks() {
  return window['go']['app']['SecOps']['GetScheduledTasks']();
}

export function GetSecurityEvents() {
  return window['go']['app']['SecOps']['GetSecurityEvents']();
}

export function GetSecurityScore() {
  return window['go']['app']['SecOps']['GetSecurityScore']();
}

export function GetSecuritySummary() {
  return window['go']['app']['SecOps']['GetSecuritySummary']();
}

export function GetUsers() {
  return window['go']['app']['SecOps']['GetUsers']();
}

export function SetFirewallRuleState(arg1, arg2) {
  return window['go']['app']['SecOps']['SetFirewallRuleState'](arg1, arg2);
}
