// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBatteryInfo() {
  return window['go']['app']['SysOps']['GetBatteryInfo']();
}

export function GetCPUExtended() {
  return window['go']['app']['SysOps']['GetCPUExtended']();
}

export function GetCPUInfo() {
  return window['go']['app']['SysOps']['GetCPUInfo']();
}

export function GetDiskIO() {
  return window['go']['app']['SysOps']['GetDiskIO']();
}

export function GetDiskInfo() {
  return window['go']['app']['SysOps']['GetDiskInfo']();
}

export function GetGPUInfo() {
  return window['go']['app']['SysOps']['GetGPUInfo']();
}

export function GetHardwareInfo() {
  return window['go']['app']['SysOps']['GetHardwareInfo']();
}

export function GetHistoricalHealthReport(arg1) {
  return window['go']['app']['SysOps']['GetHistoricalHealthReport'](arg1);
}

export function GetLoggedInUsers() {
  return window['go']['app']['SysOps']['GetLoggedInUsers']();
}

export function GetMemoryInfo() {
  return window['go']['app']['SysOps']['GetMemoryInfo']();
}

export function GetPerformanceStats() {
  return window['go']['app']['SysOps']['GetPerformanceStats']();
}

export function GetProcessTree() {
  return window['go']['app']['SysOps']['GetProcessTree']();
}

export function GetProcessTreeGraph() {
  return window['go']['app']['SysOps']['GetProcessTreeGraph']();
}

export function GetRecommendations() {
  return window['go']['app']['SysOps']['GetRecommendations']();
}

export function GetScheduledTasks() {
  return window['go']['app']['SysOps']['GetScheduledTasks']();
}

export function GetSystemInfo() {
  return window['go']['app']['SysOps']['GetSystemInfo']();
}

export function GetSystemLogs(arg1, arg2) {
  return window['go']['app']['SysOps']['GetSystemLogs'](arg1, arg2);
}

export function GetTopProcesses(arg1) {
  return window['go']['app']['SysOps']['GetTopProcesses'](arg1);
}

export function ListAllProcesses(arg1) {
  return window['go']['app']['SysOps']['ListAllProcesses'](arg1);
}

export function ListHistoricalHealthReports() {
  return window['go']['app']['SysOps']['ListHistoricalHealthReports']();
}

export function RunExtendedDiagnostics() {
  return window['go']['app']['SysOps']['RunExtendedDiagnostics']();
}

export function RunSystemAction(arg1) {
  return window['go']['app']['SysOps']['RunSystemAction'](arg1);
}
