// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBatteryInfo() {
  return window['go']['app']['SysOps']['GetBatteryInfo']();
}

export function GetCPUInfo() {
  return window['go']['app']['SysOps']['GetCPUInfo']();
}

export function GetDiskInfo() {
  return window['go']['app']['SysOps']['GetDiskInfo']();
}

export function GetGPUInfo() {
  return window['go']['app']['SysOps']['GetGPUInfo']();
}

export function GetMemoryInfo() {
  return window['go']['app']['SysOps']['GetMemoryInfo']();
}

export function GetProcessTree() {
  return window['go']['app']['SysOps']['GetProcessTree']();
}

export function GetRecommendations() {
  return window['go']['app']['SysOps']['GetRecommendations']();
}

export function GetSystemInfo() {
  return window['go']['app']['SysOps']['GetSystemInfo']();
}

export function GetTopProcesses(arg1) {
  return window['go']['app']['SysOps']['GetTopProcesses'](arg1);
}

export function ListAllProcesses(arg1) {
  return window['go']['app']['SysOps']['ListAllProcesses'](arg1);
}
