// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {common} from '../models';

export function DownloadLHM():Promise<app.LHMStatusResult>;

export function GetBatteryInfo():Promise<app.BatteryInfo>;

export function GetCPUExtended():Promise<app.CPUExtendedInfo>;

export function GetCPUInfo():Promise<app.CPUInfo>;

export function GetDiskIO():Promise<app.DiskIOData>;

export function GetDiskInfo():Promise<app.DiskInfo>;

export function GetGPUInfo():Promise<app.GPUInfo>;

export function GetHardwareInfo():Promise<app.HardwareInfo>;

export function GetHistoricalHealthReport(arg1:string):Promise<app.ExtendedDiagnosticResult>;

export function GetInstalledPackages():Promise<Array<app.PackageManagerData>>;

export function GetLHMAuthorization():Promise<app.LHMAuthorization>;

export function GetLHMStatus():Promise<app.LHMStatusResult>;

export function GetLoggedInUsers():Promise<Array<app.LoggedInUserData>>;

export function GetMemoryInfo():Promise<app.MemoryInfo>;

export function GetPerformanceStats():Promise<app.PerformanceData>;

export function GetProcessTree():Promise<Array<app.ProcessInfo>>;

export function GetProcessTreeGraph():Promise<app.ProcessNode>;

export function GetRecommendations():Promise<Array<app.SystemRecommendation>>;

export function GetScheduledTasks():Promise<Array<app.ScheduledTaskData>>;

export function GetSystemInfo():Promise<app.SystemInfo>;

export function GetSystemLogs(arg1:number,arg2:string):Promise<app.SystemLogsResultData>;

export function GetTopProcesses(arg1:number):Promise<Array<app.ProcessInfo>>;

export function ListAllProcesses(arg1:number):Promise<Array<app.ProcessInfo>>;

export function ListHistoricalHealthReports():Promise<Array<common.ReportRecord>>;

export function RunExtendedDiagnostics():Promise<app.ExtendedDiagnosticResult>;

export function RunSystemAction(arg1:string):Promise<common.ActionPreview>;

export function StartLHM():Promise<app.LHMStatusResult>;

export function StopLHM():Promise<app.LHMStatusResult>;
