// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ExplainEvents(arg1:Array<string>):Promise<string>;

export function GetRecentEvents(arg1:number):Promise<Array<app.TimelineEvent>>;

export function GetRelatedEvents(arg1:string):Promise<Array<app.TimelineEvent>>;

export function GetTimelineCategories():Promise<Array<string>>;

export function GetTimelineEventByID(arg1:string):Promise<app.TimelineEvent>;

export function GetTimelineEvents(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<app.TimelineEvent>>;

export function GetTimelineSummary(arg1:number):Promise<Record<string, number>>;
