// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExplainEvents(arg1) {
  return window['go']['app']['Timeline']['ExplainEvents'](arg1);
}

export function GetRelatedEvents(arg1) {
  return window['go']['app']['Timeline']['GetRelatedEvents'](arg1);
}

export function GetTimelineCategories() {
  return window['go']['app']['Timeline']['GetTimelineCategories']();
}

export function GetTimelineEventByID(arg1) {
  return window['go']['app']['Timeline']['GetTimelineEventByID'](arg1);
}

export function GetTimelineEvents(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Timeline']['GetTimelineEvents'](arg1, arg2, arg3, arg4);
}

export function GetTimelineSummary(arg1) {
  return window['go']['app']['Timeline']['GetTimelineSummary'](arg1);
}
