// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCustomWorkflow(arg1) {
  return window['go']['app']['WorkflowAPI']['DeleteCustomWorkflow'](arg1);
}

export function ExecuteWorkflow(arg1) {
  return window['go']['app']['WorkflowAPI']['ExecuteWorkflow'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['app']['WorkflowAPI']['GetWorkflow'](arg1);
}

export function ListWorkflows() {
  return window['go']['app']['WorkflowAPI']['ListWorkflows']();
}

export function RegisterDefaultWorkflows() {
  return window['go']['app']['WorkflowAPI']['RegisterDefaultWorkflows']();
}

export function SaveCustomWorkflow(arg1) {
  return window['go']['app']['WorkflowAPI']['SaveCustomWorkflow'](arg1);
}
