// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function DeleteCustomWorkflow(arg1:string):Promise<void>;

export function ExecuteWorkflow(arg1:string):Promise<common.WorkflowDefinition>;

export function GetWorkflow(arg1:string):Promise<common.WorkflowDefinition>;

export function ListWorkflows():Promise<Array<common.WorkflowDefinition>>;

export function RegisterDefaultWorkflows():Promise<void>;

export function SaveCustomWorkflow(arg1:common.WorkflowDefinition):Promise<void>;
