// Code generated by tool. DO NOT EDIT.
//go:build !windows

package common

// LHMStatus represents the current state of the bundled LHM instance.
type LHMStatus struct {
	Available  bool   `json:"available"`
	Running    bool   `json:"running"`
	NeedsAdmin bool   `json:"needsAdmin"`
	Version    string `json:"version"`
	Path       string `json:"path"`
	Error      string `json:"error,omitempty"`
}

// LHMManager is a no-op stub on non-Windows platforms.
type LHMManager struct{}

var lhmStubInstance = &LHMManager{}

// GetLHMManager returns a no-op manager on non-Windows platforms.
func GetLHMManager() *LHMManager {
	return lhmStubInstance
}

// Status returns unavailable on non-Windows.
func (m *LHMManager) Status() LHMStatus {
	return LHMStatus{Available: false, Running: false}
}

// IsAvailable returns false on non-Windows.
func (m *LHMManager) IsAvailable() bool { return false }

// IsRunning returns false on non-Windows.
func (m *LHMManager) IsRunning() bool { return false }

// BinaryPath returns empty on non-Windows.
func (m *LHMManager) BinaryPath() string { return "" }

// DirPath returns empty on non-Windows.
func (m *LHMManager) DirPath() string { return "" }

// Download returns an error on non-Windows.
func (m *LHMManager) Download(ctx interface{}, progress interface{}) error {
	return nil
}

// Start returns an error on non-Windows.
func (m *LHMManager) Start() error { return nil }

// Stop is a no-op on non-Windows.
func (m *LHMManager) Stop() error { return nil }

// Ensure returns an error on non-Windows.
func (m *LHMManager) Ensure(ctx interface{}, userConsent interface{}) error {
	return nil
}

// Remove is a no-op on non-Windows.
func (m *LHMManager) Remove() error { return nil }
