// Code generated by tool. DO NOT EDIT.
//go:build !windows

package common

import "time"

// WMIQueryWithTimeout is not available on this platform.
func WMIQueryWithTimeout(query string, dst interface{}, timeout time.Duration) error {
	return nil
}

// WMIQueryNamespaceWithTimeout is not available on this platform.
func WMIQueryNamespaceWithTimeout(query string, dst interface{}, namespace string, timeout time.Duration) error {
	return nil
}
